# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type_id',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, 'vip用户'), (3, '超级用户')], default=1),
        ),
    ]
